In [2]:
import pandas as pd
obj = pd.Series([4,5,-3,11])
print(obj)

0     4
1     5
2    -3
3    11
dtype: int64


In [3]:
#pandas Series has 2 things in one object
#1 values
#2 index


In [4]:
obj.values

array([ 4,  5, -3, 11], dtype=int64)

In [5]:
obj.index

RangeIndex(start=0, stop=4, step=1)

In [6]:
# we can change the index of our series before and after the creation of our series

In [7]:
obj.index = ['a','b','c','d']

In [8]:
obj

a     4
b     5
c    -3
d    11
dtype: int64

In [9]:
sales = pd.Series([100,200,300],index=['jan','feb','mar'])

In [10]:
sales

jan    100
feb    200
mar    300
dtype: int64

In [11]:
print(sales.values)
print(sales.index)

[100 200 300]
Index(['jan', 'feb', 'mar'], dtype='object')


In [12]:
# we can also give the name of aur series 

In [13]:
sales = pd.Series([100,200,300],index=['jan','feb','mar'],name="3 months salary")

In [14]:
print(sales)

jan    100
feb    200
mar    300
Name: 3 months salary, dtype: int64


In [15]:
# creating a pandas series to store canteen data of each day (for one week)

In [16]:
sales = pd.Series([70,58,49,64,92,27,0],index=['mon','tue','wed','thu','fri','sat','sun'],name="number of sandwitches sold")

In [17]:
sales

mon    70
tue    58
wed    49
thu    64
fri    92
sat    27
sun     0
Name: number of sandwitches sold, dtype: int64

In [18]:
#pd.Series(values,index,name) 
#values can be string or integer or any other datatype simultaneously
#sales = pd.Series([70,None,49,64,True,27,'canteen was closed on wednesday'],index=['mon','tue','wed','thu','fri','sat','sun'],name="number of sandwitches sold")


In [19]:
#sales

In [20]:
#acessing stored data

In [21]:
print(sales[0])  # similar to accessing data in numpy ARRAY

70


In [22]:
print(sales['mon'])  # accessing data of pandas series
                    # when data is too large we use index to access data

70


In [23]:
# accessing multiple values

In [24]:
print(sales[[0,3]])

mon    70
thu    64
Name: number of sandwitches sold, dtype: int64


In [25]:
print(sales[['mon','thu']])

mon    70
thu    64
Name: number of sandwitches sold, dtype: int64


In [26]:
# accessing particular values based on some condition

In [27]:
print(sales[sales>60])

mon    70
thu    64
fri    92
Name: number of sandwitches sold, dtype: int64


In [28]:
# suppose our target is to acheive twice the sales of aur present sales
#(IT IS ONLY our target we can not change our original sales)

In [29]:
print(sales*2)   # targeted_sales

mon    140
tue    116
wed     98
thu    128
fri    184
sat     54
sun      0
Name: number of sandwitches sold, dtype: int64


In [30]:
print(sales) # our original sales

mon    70
tue    58
wed    49
thu    64
fri    92
sat    27
sun     0
Name: number of sandwitches sold, dtype: int64


In [31]:
# suppose our target is acheived now our sales are doubled

In [32]:
sales = sales*2 # without loops !!! 

In [33]:
sales

mon    140
tue    116
wed     98
thu    128
fri    184
sat     54
sun      0
Name: number of sandwitches sold, dtype: int64

In [34]:
# we are reported today that
# our 2 daily customers were not loyal to us this week:
sales-2

mon    138
tue    114
wed     96
thu    126
fri    182
sat     52
sun     -2
Name: number of sandwitches sold, dtype: int64

In [35]:
sales

mon    140
tue    116
wed     98
thu    128
fri    184
sat     54
sun      0
Name: number of sandwitches sold, dtype: int64

In [36]:
# 3 more customers join us on mondays 
sales['mon'] = sales['mon']+3


In [46]:
sales

mon    143
tue    116
wed     98
thu    128
fri    184
sat     54
sun      0
Name: number of sandwitches sold, dtype: int64

In [38]:
# checking if a certain index exsist in a list

In [39]:
'mon' in sales   #in operator

True

In [40]:
# we can make pandas series also by using numpy array

In [41]:
import numpy as np
scores = np.array([70,30,45,60])
players = np.array(['vardy','maddison','kalechi','evans'])

In [42]:
obj2 = pd.Series(scores,index=players,name="premier league scorers")
obj2

vardy       70
maddison    30
kalechi     45
evans       60
Name: premier league scorers, dtype: int32

In [43]:
# we can also create series from python dictionary

In [44]:
scores={'vardy':70,'maddison':60,'kalechi':26,'evans':19}
obj3 = pd.Series(scores)
obj3

vardy       70
maddison    60
kalechi     26
evans       19
dtype: int64

In [45]:
print(obj3.index)
print(obj3.values)

Index(['vardy', 'maddison', 'kalechi', 'evans'], dtype='object')
[70 60 26 19]


In [137]:
# values will be mapped to indxes according to the dictionary,if we change the sequence of index of series the association
# will not be changed only the order of rows will be changed due to change in index while creating the series

In [138]:
scores={'vardy':70,'maddison':60,'kalechi':26,'evans':19}
obj3 = pd.Series(scores,index=['maddison','vardy','evans','kalechi'])
obj3

maddison    60
vardy       70
evans       19
kalechi     26
dtype: int64

**Source of data for pandas Series**
* manually provide data in pd.Series()
* numpy array
* python list
* python dictionary

In [139]:
#checking null

In [141]:
scores={'vardy':70,'maddison':60,'kalechi':26,'evans':19}
obj4 = pd.Series(scores,index=['maddison','vardy','evans','kalechi','aguero'])
obj4

maddison    60.0
vardy       70.0
evans       19.0
kalechi     26.0
aguero       NaN
dtype: float64

In [154]:
obj4.isnull()   # method

maddison    False
vardy       False
evans       False
kalechi     False
aguero       True
dtype: bool

In [155]:
pd.isnull(obj4)  #Function

maddison    False
vardy       False
evans       False
kalechi     False
aguero       True
dtype: bool

In [161]:
obj4.name="premier league scorers"
obj4.index.name = "players"

In [162]:
obj4

players
maddison    60.0
vardy       70.0
evans       19.0
kalechi     26.0
aguero       NaN
Name: premier league scorers, dtype: float64